### ISSUE TITLE
Unexpected token: operator (>)

### ISSUE THREAD

**Issue by afuno** [SevenOutman/vue-aplayer#17]
Error:

> Unexpected token: operator (>) [./node_modules/vue-aplayer/src/utils.js:11,0][posts-65b31383fe39c33c7e6b.js:52227,26]

I use almost pure Rails 5.1.4.

**Comment by SevenOutman** [comment]
@afuno You are supposed to use `dist/vue-aplayer.min.js` rather than any js files in `src`. 

If you are using npm and ES modules, you should import `vue-aplayer` as described [here](https://github.com/SevenOutman/vue-aplayer#usage).

 If you are not familiar with npm-based frontend development, you can just add a `<script>` tag in your template file (e.g. html file) like this:

    <script type="text/javascript" "src="//unpkg.com/vue-aplayer/dist/vue-aplayer.min.js" />

Hope this helps.

**Comment by afuno** [comment]
@SevenOutman I use as an ES module.

**Comment by SevenOutman** [comment]
@afuno I see. Did you set up your `webpack` to use [`vue-loader`](https://github.com/vuejs/vue-loader) to process `.vue` files?
You can find an example config at my [webpack.config.js:Line 15](https://github.com/SevenOutman/vue-aplayer/blob/develop/webpack.config.js#L15)

**Comment by afuno** [comment]
@SevenOutman The problem arises from pure Rails 5.1.4. Together with Rails was installed Webpack(er). I have no problem with any other installed package.

**Comment by SevenOutman** [comment]
@afuno So you mean you haven’t done anything with webpack, INCLUDING configuring it to be capable to work with Vue(which you should do), right?

If so, check out the link in my previous comment, or refer to Vue docs to see what you are supposed to do with webpack so that it can work with Vue correctly.

**Comment by SevenOutman** [comment]
Should be fixed in 1.0.2 update
