### ISSUE TITLE
build error in vue-cli init project 

### ISSUE THREAD

**Issue by cobola** [SevenOutman/vue-aplayer#18]
<img width="1109" alt="2018-01-19 08 53 35" src="https://user-images.githubusercontent.com/4435875/35129510-eb505cd0-fcf6-11e7-8d0d-584c1abcc5fc.png">

<img width="888" alt="2018-01-19 08 59 02" src="https://user-images.githubusercontent.com/4435875/35129531-078876f8-fcf7-11e7-9a36-6f1d3e2374a5.png">

<img width="533" alt="2018-01-19 08 59 43" src="https://user-images.githubusercontent.com/4435875/35129552-1e2279b8-fcf7-11e7-9c43-65f19f12349f.png">

**Comment by SevenOutman** [comment]
@cobola Sorry for my late reply. This problem is caused by missing `sass-loader`, which should be listed in `vue-aplayer`'s `dependencies` but is currently listed as a dev dependency. I'm gonna fix this very soon.

A quick fix is to import vue-aplayer from 'vue-aplayer/dist/vue-aplayer.min.js' instead of 'vue-aplayer' which refers to 'vue-aplayer/src/vue-aplayer.vue' and requires that loader.

**Comment by SevenOutman** [comment]
@cobola It's been fixed in 1.0.2
