### ISSUE TITLE
listFolded prop is not in aplayer-list.vue

### ISSUE THREAD

**Issue by shilik** [SevenOutman/vue-aplayer#28]
Thank you very much  for your quick response and fix.  When I looked into the source code of aplayer-list.vue, listFolded prop was still not defined, though it said 'listFolded prop added'. After updating to ver 1.4.1, listFolded prop didn't work on my project. Is the file the latest one?

**Comment by SevenOutman** [comment]
@shilik You can look into commit f91ff7743f30e2b3a967f24a4852f875092e4ab2 to see how `listFolded` is implemented. It has nothing to do with `aplayer-list.vue`.

In `vue-aplayer.vue`, there is a state named `showList` indicating whether playlist is folded or not. Originally its initial value is `true`, which means show the playlist initially by default. Since `v1.4.1` it initiates with the `listFolded` prop value. So if you pass `listFolded=true` to Vue-APlayer, you have a folded playlist.

**Comment by shilik** [comment]
Great, Thank you for the detailed explanation, It's my fault to work on a wrong project without latest vue-aplyer. :P  It is now working like a charm! :)
