### ISSUE TITLE
Not playing - Any changes made recently?

### ISSUE THREAD

**Issue by adilk2005** [SevenOutman/vue-aplayer#76]
Hi, I saw your player and think it's great.

I tried following the instructions and have been tinkering with them for some time now. I can't get it to work. Have there been any changes to the code recently which could cause this issue?

**Comment by SevenOutman** [comment]
@adilk2005 Glad you like it! But I can't help you if I don't clearly understand your issue. Could you just show me your code and explain what's the expected/actual behavior?

**Comment by adilk2005** [comment]
Hi, thanks for getting back to me so quickly.

Js Fiddle Link: https://jsfiddle.net/adilk/0aowdL36/1/
I've outlined the steps taken in the comments of the code. 

Expected outcome: My goal is to use the "featured" player outlined on this page. https://vue-aplayer.js.org/

**Comment by SevenOutman** [comment]
@adilk2005 In this specific fiddle the problem is that `VueAPlayer` variable is not assigned correctly - and it's a bug from this library. I'm fixing this in next patch release. A quick fix to this is use `VueAPlayer.default`.
```javascript
Vue.component('aplayer', VueAPlayer.default)
```

Or you can just use it normally with npm, as this only happens when you use Vue-APlayer from CDN.
